### ISSUE TITLE
Hi Edikevich

### ISSUE THREAD

**Issue by dredknight** [edikevich/katacoda-scenarios#1]
Hey [edikevich](https://github.com/edikevich)!

I contact you about repository https://github.com/edikevich/cloud_scripts.
It is a fork of one of my repositories that is no longer present. 

Could you make it private so it is not available publicly? I ask because it contains a few email references of my previous employer.
I will be most grateful if you do that!

**Comment by edikevich** [comment]
Hi. Sure, no problem)

**Comment by dredknight** [comment]
Thank you!
